@OnlineCourseReviews.Api_HostAddress = http://localhost:5273

GET {{OnlineCourseReviews.Api_HostAddress}}/api/reviews
Accept: application/json

###

@ReviewId=9cc01b65-c4d6-4ee5-83a0-8362c7db8884
GET {{OnlineCourseReviews.Api_HostAddress}}/api/reviews/{{ReviewId}}
Accept: application/json

###

POST {{OnlineCourseReviews.Api_HostAddress}}/api/reviews
Accept: application/json
Content-Type: application/json

{
  "courseId": "00000000-0000-0000-0000-00000000000c",
  "userId": "mariabaqir@hotmail.com",
  "reviewText": "Enlightening course!",
  "rating": 5,
  "isRecommended": true,
  "isCourseCompleted": true,
  "pricePaid": 40.000000,
  "discountCodeUsed": "DISCOUNT7"
}

###

@ReviewToUpdateId=4bcaf969-ece1-42bf-9904-6ac0ed7426cd
PUT {{OnlineCourseReviews.Api_HostAddress}}/api/reviews/{{ReviewToUpdateId}}
Accept: application/json
Content-Type: application/json

{
  "id": "{{ReviewToUpdateId}}",
  "courseId": "00000000-0000-0000-0000-00000000000c",
  "courseName": "Introduction to Data Science",
  "userId": "mariabaqir@hotmail.com",
  "reviewText": "Very enlightening course!",
  "rating": 4,
  "isRecommended": true,
  "isCourseCompleted": true,
  "pricePaid": -50.000000,
  "discountCodeUsed": "DISCOUNT5"
}

###

@ReviewToDeleteId=ae549ef8-d144-4cca-a574-961655dc96e4
DELETE {{OnlineCourseReviews.Api_HostAddress}}/api/reviews/{{ReviewToDeleteId}}
Accept: application/json

###