@OnlineCourseReviews.Api_HostAddress = https://localhost:7112

GET {{OnlineCourseReviews.Api_HostAddress}}/api/reviews
Accept: application/json

###

@ReviewId=9cc01b65-c4d6-4ee5-83a0-8362c7db8884
GET {{OnlineCourseReviews.Api_HostAddress}}/api/reviews/{{ReviewId}}
Accept: application/json

###

POST {{OnlineCourseReviews.Api_HostAddress}}/api/reviews
Accept: application/json
Content-Type: application/json

{
  "courseId": "00000000-0000-0000-0000-00000000000c",
  "userId": "mariabaqir@hotmail.com",
  "reviewText": "Enlightening course!",
  "rating": 5,
  "isRecommended": true,
  "isCourseCompleted": true,
  "pricePaid": 40.000000,
  "discountCodeUsed": "DISCOUNT7"
}

###

@ReviewToUpdateId=4bcaf969-ece1-42bf-9904-6ac0ed7426cd
PUT {{OnlineCourseReviews.Api_HostAddress}}/api/reviews/{{ReviewToUpdateId}}
Accept: application/json
Content-Type: application/json

{
  "id": "{{ReviewToUpdateId}}",
  "courseId": "00000000-0000-0000-0000-00000000000c",
  "courseName": "Introduction to Data Science",
  "userId": "mariabaqir@hotmail.com",
  "reviewText": "Very enlightening course!",
  "rating": 4,
  "isRecommended": true,
  "isCourseCompleted": true,
  "pricePaid": -50.000000,
  "discountCodeUsed": "DISCOUNT5"
}

###

@ReviewToDeleteId=ae549ef8-d144-4cca-a574-961655dc96e4
DELETE {{OnlineCourseReviews.Api_HostAddress}}/api/reviews/{{ReviewToDeleteId}}
Accept: application/json

###

POST {{OnlineCourseReviews.Api_HostAddress}}/api/users
Accept: application/json
Content-Type: application/json

{
  "firstName": "Sean",
  "lastName": "Schwabenlander",
  "emailAddress": "sean@test.com",
  "password": "P@ssw0rd"
}

###

POST {{OnlineCourseReviews.Api_HostAddress}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "emailAddress": "sean@test.com",
  "password": "P@ssw0rd"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzZWFuQHRlc3QuY29tIiwiZXhwIjoxNzE1Mzk4ODI4LCJpYXQiOjE3MTUzMTI0MjgsIm5iZiI6MTcxNTMxMjQyOH0.kcgKac0KgpYn-_LY0uRkgox1Q1meG_k27fzXRXaXB1k

# Add course

POST {{OnlineCourseReviews.Api_HostAddress}}/api/courses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "schoolId": "00000000-0000-0000-0000-000000000011",
  "title": "Introduction to Data Science",
  "description": "Learn the basics of data science",
  "instructor": "John Doe",
  "price": 50.000000,
  "url": "https://www.udemy.com/introduction-to-data-science"
}

### Get all courses

GET {{OnlineCourseReviews.Api_HostAddress}}/api/courses
Accept: application/json
Authorization: Bearer {{token}}

### Get course by id

@CourseId=277c1a43-9171-4db5-9cbf-4139a3035a62
GET {{OnlineCourseReviews.Api_HostAddress}}/api/courses/{{CourseId}}
Accept: application/json
Authorization: Bearer {{token}}

### Delete course

@CourseIdToDelete=277c1a43-9171-4db5-9cbf-4139a3035a62
DELETE {{OnlineCourseReviews.Api_HostAddress}}/api/courses/{{CourseIdToDelete}}
Accept: application/json
Authorization: Bearer {{token}}
